# Generated by Django 4.1.1 on 2022-10-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Editorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name_plural": "Editorial",
            },
        ),
        migrations.DeleteModel(
            name="analisis",
        ),
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name_plural": "Autores"},
        ),
        migrations.AlterModelOptions(
            name="libro",
            options={"verbose_name_plural": "Libros"},
        ),
        migrations.RenameField(
            model_name="libro",
            old_name="género",
            new_name="genero",
        ),
        migrations.RenameField(
            model_name="libro",
            old_name="publicación",
            new_name="publicacion",
        ),
        migrations.RenameField(
            model_name="libro",
            old_name="título",
            new_name="titulo",
        ),
    ]
